# -*- mode: ruby -*-
# vi: set ft=ruby :

# define box. https://app.vagrantup.com/bento/boxes/debian-11 https://developer.hashicorp.com/vagrant/docs/boxes
VAGRANT_BOX = "bento/debian-11"

# define provider
PROVIDER = "virtualbox"

# define characteristics of virtual machine
MEM = 2048
CPU = 2
NAME = "Scornhol"
NAME2 = "Schung"
SERVER_IP = "192.168.56.110"
SCRIPT = "./scripts/server.sh"

Vagrant.configure("2") do |config|

  config.vm.box = VAGRANT_BOX
    
  config.vm.provider PROVIDER do |vb|
    # define resources 
    vb.memory = MEM
    vb.cpus = CPU
    vb.name = NAME
    # connect with SSH on both machines with no password
    id_rsa_pub = File.read("#{Dir.home}/.ssh/id_rsa.pub")
    config.vm.provision "copy ssh public key", type: "shell", inline: "echo \"#{id_rsa_pub}\" >> /home/vagrant/.ssh/authorized_keys"
  end # provider
  
  config.vm.define NAME2
  config.vm.hostname = NAME
  config.vm.network "private_network", ip: SERVER_IP
  config.vm.synced_folder ".", "/vagrant", type: PROVIDER, create: true
  config.vm.provision "shell", privileged: true, path: SCRIPT, args: SERVER_IP

end # Vagrant.configure